---
# file: ansible-postgresql-el/tasks/configure.yml
    
- name: Initialize PostgreSQL server
  sudo: yes
  command: "{{ pgsql_initdb_path }} initdb creates={{ pgsql_data_directory }}/postgresql.conf"
  environment: 
    PGSETUP_INITDB_OPTIONS: "--pgdata={{ pgsql_data_directory }}"
  notify:
    - Restart PostgreSQL
    
- name: Write PostgreSQL client authentication file (pg_hba.conf)
  template:
    src: pg_hba.conf.j2
    dest: "{{ pgsql_data_directory }}/pg_hba.conf"
    owner: "{{ pgsql_service_user }}"
    group: "{{ pgsql_service_group }}"
    mode: 0640
  notify:
    - Restart PostgreSQL
    
- name: Write PostgreSQL configuration file (postgresql.conf)
  template:
    src: postgresql.conf.j2
    dest: "{{ pgsql_data_directory }}/postgresql.conf"
    owner: "{{ pgsql_service_user }}"
    group: "{{ pgsql_service_group }}"
    mode: 0640
  notify:
    - Restart PostgreSQL

- name: Create directory for additional configuration files
  file:
    name: "{{pgsql_data_directory}}/conf.d"
    state: directory
    owner: "{{ pgsql_service_user }}"
    group: "{{ pgsql_service_group }}"
    mode: 0755